import axios from "axios";
import Head from "next/head";
import { spotifyAuthURL } from "./api/axios";
// import Image from "next/image";
// import { Inter } from "@next/font/google";
// import styles from '@/styles/Home.module.css'

export default function Home() {
  const spotifyLoginHandler = () => {
    if (process.env.SPOTIFY_ENDPOINT_URL) {
      axios.get(spotifyAuthURL).then((e) => {
        console.log(e);
      });
    }
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <button onClick={spotifyLoginHandler}>Spotify Login</button>
      </div>
    </>
  );
}
