import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import Cookie from "./api/cookie";
import { searchItems, skipToNext } from "@/hook/spotify";
import Image from "next/image";
import { Box, Card, Container, Grid, Paper, Typography } from "@mui/material";
import AddCircleOutlineIcon from "@mui/icons-material/AddCircleOutline";

export default function Home() {
  const router = useRouter();
  const [token, setToken] = useState<string>("");
  const [test, setTest] = useState<string>("");

  const spotifyLoginHandler = () => {
    const spotifyAuthorizeURL = "https://accounts.spotify.com/authorize/";
    const clientId = process.env.SPOTIFY_CLIENT_ID || "";
    const redirectURL = process.env.SPOTIFY_REDIRECT_URL || "";
    const scopes = `streaming user-read-playback-position user-modify-playback-state user-read-playback-state user-read-private user-read-email app-remote-control`;
    const state = "123";

    const spotifyAuthQuery = `?client_id=${encodeURIComponent(
      clientId
    )}&redirect_uri=${encodeURIComponent(
      redirectURL
    )}&scope=${encodeURIComponent(scopes)}&response_type=token&state=${state}`;

    window.location.href = spotifyAuthorizeURL + spotifyAuthQuery;
  };

  useEffect(() => {
    const accessToken = Cookie.getCookie("accessToken");
    if (accessToken) setToken(accessToken);
  }, [router.isReady]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {!token && <button onClick={spotifyLoginHandler}>Spotify Login</button>}
      </div>
    </>
  );
}
